### ISSUE TITLE
Greater Than Four Lights May Be Unstable

### ISSUE THREAD

**Issue by nfsmaster208** [stringandstickytape/MaxLifx#8]
Upon opening a thread for screen colour response or sound response, a maximum of seven (byte limitation?) lights may be addressed simultaneously. However, saving the thread, which initially appears to work, is where the issue becomes problematic. After "saving" the thread, clicking on load thread kills the existing "saved" thread process, and the previously "saved" thread no longer exists.

I have added several lights to my room, and have now more than doubled the total number of lights I wish to use simultaneously (from four to ten). Why? Because I love MaxLifx! I also won an eBay auction, and got the lights at a steep discount (woo!)

My best guess is the reason there is an issue saving and/or loading threads with more than the number of lights I have been using is that the number of lights are not generally expected to exceed a byte in size. The overall number of lights in my home has gone up by 10 now, so this is a different game. Let me know if there's anything I can try out to help with the troubleshooting.

A couple of additional notes, the total number of discovered lights now also exceeds a byte, and before I clicked discover, I was able to successfully run the four lights by loading my previously working threads. Now, if I attempt to open said threads, nothing happens. On another, less important note, it appears the new Lifx Mini lamps are not supported by MaxLifx. This may require information by LIFX to fix, so that's low priority for me here.

Thanks, @stringandstickytape, for everything you do. If there is any chance you can get around to this, that'd be super cool!

**Comment by Clarkinator** [comment]
So it's probably not a light issue, have you tried turning off a few until they register? Also as a note, a single byte is 128, a half byte is 8.

**Comment by nfsmaster208** [comment]
^ The LIFX mini? There's only one of those, and that's the only one that doesn't appear.

**Comment by Clarkinator** [comment]
What I mean is have you tried turning lights off until they register in the program, so you only have 4 discoverable and see if that works and then adding a 5th causes it to not register?

The mini is a sperate issue.

**Comment by nfsmaster208** [comment]
Ah, okay. I think I see what you mean. So yes, I have 14 discovered lights, of the 15 current that I have installed. My intention is to use nine lights simultaneously in nearly any configuration. The reason for this is I have some white LIFX lamps elsewhere in the house that do not need to be connected to the app at any time. I will see what turning off some other lamps will do for stability in the meanwhile, and attempt to rediscover, setup a new thread, load, and test from there. Thanks!

**Comment by nfsmaster208** [comment]
Okay, I realize I didn't try the number one troubleshooting step for all technology ever: "Did you turn it off and then back on?"

Exiting MaxLifx after Discovery is MANDATORY in order to add new lights to threads, even if they appear to be recognized normally. Otherwise, you experience the behaviors I outlined earlier.

**Comment by Clarkinator** [comment]
Did that fix both issues by chance or just the more lights issue?

**Comment by nfsmaster208** [comment]
Just the more lights issue, I'm afraid. It seems the new minis use a
different protocol.

**Comment by stringandstickytape** [comment]
Could be this? https://community.lifx.com/t/lifx-gu10-downlight/3565/16

"markhLIFX Employee Dec '17
@lightbow yes, there is another update for the LIFX Mini range that will fix that issue with discovery. It is currently in internal testing."

**Comment by nfsmaster208** [comment]
I apologize for not posting sooner. ^ The Mini firmware update RESOLVED the issue completely. It works as expected, and no further change is required. THANK YOU!
